 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  aircraft_caption_ins: # name of the dataset builder 
    dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_train.json
          # md5: aa31ac474cf6250ebb81d18348a07ed8
          storage:  aircraft_cap_instruction/annotations/js_img_caption800_dialogue4k_v0.json
        val:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_val.json
          # md5: b273847456ef5580e33713b1f7de52a0
          # storage: med_cap_instruction/annotations/med_image_sjwk_cap_ins_13k_v1_valid.json
          storage:  aircraft_cap_instruction/annotations/js_img_caption800_dialogue4k_v0_valid.json
        test:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_test.json
          # md5: 3ff34b0ef2db02d01c37399f6a2a6cd1
          # storage: med_cap_instruction/annotations/med_image_sjwk_cap_ins_13k_v1_valid.json
          storage:  aircraft_cap_instruction/annotations/js_img_caption800_dialogue4k_v0_valid.json

      images:
        storage: aircraft_cap_instruction/
