 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  med_caption: # name of the dataset builder
    dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          # url: "/data2/shij/data/Med2/raw_data/train_texts.json"
          # storage: med2/annotations/med_train.json
          url: "/data2/shij/data/Med2/raw_data/train_texts_with_id.json"
          # storage: med2/annotations/med_train_with_id.json
          # storage: med2/annotations/med2_qa_with_id.json
          # storage: med2/annotations/med_cap_5qa_with_id.json
          storage: med2/annotations/med_cap_3x1900qa_1.0xalpaca_with_id.json
        val:
          url: "/data2/shij/data/Med2/raw_data/valid_texts.json"
          storage: med2/annotations/med_val.json
        test:
          url: "/data2/shij/data/Med2/raw_data/test_texts.json"
          storage: med2/annotations/med_test.json
      images:
        storage: med2/images/
