 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  wukong_caption: # name of the dataset builder
    dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: "/data2/shij/data/Med2/raw_data/train_texts.json"
          storage: wukong/annotations/caption_wukong_1000w_v0.json
          # storage: wukong/annotations/caption_wukong_v0_300w.json
          #storage: wukong/annotations/caption_wukong_v1_5w.json
          # storage: wukong/annotations/caption_wukong_v1_1000.json
          # storage: wukong/annotations/caption_wukong_valid.json
        val:
          url: "/data2/shij/data/Med2/raw_data/valid_texts.json"
          storage: wukong/annotations/caption_wukong_valid.json
        test:
          url: "/data2/shij/data/Med2/raw_data/test_texts.json"
          storage: wukong/annotations/caption_wukong_test.json

      images:
        storage: wukong/images/
