 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: pretrain_opt2.7b
  load_finetuned: False

  # pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_opt2.7b.pth"
  pretrained: ""
  finetuned: ""

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # LLAMA
  # opt_model: "facebook/opt-2.7b"

  # llama_model: "decapoda-research/llama-7b-hf"
  # llama_model: "/data/shij/llama/baichuan-7B"
  llama_model: "/data/shij/llama/baichuan-13B/Baichuan-13B-Chat"

  # generation configs
  prompt: ""
  max_txt_len: 128


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
          max_words: 128
        eval:
          name: "blip_caption"
          max_words: 128
